-- Startdatabase drills (49 uit C@ddie v338). Uitvoeren na schema.sql.

insert into drills ("id","title","main_cat","sub_cats","goal","exec","vars","dur_unit","dur_value","dur_min","audience","location","workform","grp_min","grp_max","material","age_cats","levels","phases","intensity","training_type","tags","builtin","status","owner_id","created") values
('drill_seed_01','Basistechniek lage approach','golfskills','["lageappr"]'::jsonb,'Een belangrijk onderdeel van technisch goed onderlegd zijn en vooral ook blijven is met grote regelmaat de ogenschijnlijk simpele dingen heel goed doen. Basisvoorwaarden als een goed concept hebben over wat je wilt bereiken met de bal en zodoende impact, set up, oplijnen, het vasthouden van de club en de uiteindelijke beweging passend bij het schot dienen hierbij veelvuldig de revue te passeren. Het aanleren en vervolgens goed onderhouden van jouw basistechniek van een standaard lage approach is zodoende dan ook van groot belang.','De intentie is om de bal met een lage approach te spelen (korte vluchtfase en veel rol), kies zodoende ook een situatie die daadwerkelijk uitnodigt om dit schot te spelen, een fairway ligging op ±3 meter van de rand van de green en 15-20 meter van de hole is een prima uitgangspositie. Voor deze slag gebruiken we een club met wat minder loft dan een wedge, een ijzer 9, 8 of 7 is hier goed voor te gebruiken. Leg een tourstick op de grond tussen je voeten en de bal, parallel aan de bal-doellijn. Gebruik deze tourstick om de stand van het clubblad en je lichaamslijnen te controleren en zo nodig aan te passen. Vervolgens speel je de bal naar de hole waarbij je aandacht besteed aan het hele plaatje zoals je dat met jouw coach geschetst hebt te denken aan: de intentie wat je wilt met de bal, beginstand, beweging en eindstand. Hierbij kan gedacht worden aan:

Clubblad in de richting van het doel
Smalle stand ± 1 clubhoofdbreedte tussen je voeten 
Gewicht met mate naar het voorste been door je borstbeen wat naar deze zijde te laten leunen
Vrij dicht op de bal gaan staan zodat de club wat rechterop staat
Balpositie onder borstbeen
Grip voorkant bal
Stuur de beweging voornamelijk aan vanuit je romp/torso
Gelijkmatig tempo
Zwaailengte symmetrisch houden','Vanuit deze standaarduitvoering zijn er vele variaties mogelijk, experimenteer bijvoorbeeld met de balpositie, afstand tot de bal, verschillende clubs, etc. en observeer het effect hiervan op de balvlucht en rol. Je kunt dit trainen in block vorm en dus veel ballen achter elkaar spelen, maar je zou deze sessie ook kunnen opdelen in 4x 5 ballen met telkens een kleine tussenopdracht ertussen.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_02','Airstrip','golfskills','["lageappr"]'::jsonb,'Trainen om de club in een functionele baan te laten bewegen.','Leg 2 toursticks evenwijdig op de grond als een soort landingsbaan in de richting van het doel waarbij de afstand tussen de sticks net iets breder is dan een clubhoofdbreedte en plaats een tourstick aan de voor- en achterzijde van de landingsbaan op de bal doellijn. Leg de bal midden tussen de toursticks en speel deze naar de hole met de beleving dat wanneer er een laserstraal uit de onderkant van het clubhoofd zou komen deze straal van begin tot eind tussen deze baan dan wel naar de toursticks op de bal doellijn zou blijven wijzen.','Zet de toursticks onder een flauwe hoek in de grond zodat wanneer de club in de achterzwaai teveel naar binnen of buiten afdwaalt deze de tourstick zal raken.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_03','Basistechniek hoge approach','golfskills','["hogeappr"]'::jsonb,'Een belangrijk onderdeel van technisch goed onderlegd zijn en vooral ook blijven is met grote regelmaat de ogenschijnlijk simpele dingen heel goed doen. Basisvoorwaarden als een goed concept hebben over wat je wilt bereiken met de bal en zodoende impact, set up, oplijnen, het vasthouden van de club en de uiteindelijke beweging passend bij het schot kunnen hierbij veelvuldig de revue passeren. Het aanleren en vervolgens goed onderhouden van jouw basistechniek van een standaard hoge approach is zodoende dan ook van groot belang.','De intentie is om de bal met een hoge approach te spelen (langere vluchtfase en minder rol), kies zodoende ook een situatie die daadwerkelijk uitnodigt om dit schot te spelen. Een fairway ligging op net iets minder dan de helft van de totale afstand van de rand van de green en ±15-30 meter van de hole is een prima uitgangspositie. Voor deze slag gebruiken we een sand- of lobwedge. Leg een tourstick op de grond tussen je voeten en de bal, parallel aan de bal-doellijn. Gebruik deze tourstick om de stand van het clubblad en je lichaamslijnen te controleren en zo nodig aan te passen. Vervolgens speel je de bal naar de hole waarbij je aandacht besteed aan het hele plaatje zoals je dat met jouw coach geschetst hebt te denken aan: de intentie wat je wilt met de bal, beginstand, beweging en eindstand. Hierbij kan gedacht worden aan:

Clubblad een fractie open
Smalle stand ±2 clubhoofdbreedte tussen je voeten 
Gewicht met mate naar het voorste been door je borstbeen wat naar deze zijde te laten leunen
Voorste voet een ±30 graden naar het doel gedraaid (geflared)
Balpositie onder borstbeen
Grip voorkant bal
Samenwerking van handen, armen en lichaam
Club wijst naar gesp in eindstand
Gelijkmatig tempo
Zwaailengte symmetrisch houden','Vanuit deze standaarduitvoering zijn er vele variaties mogelijk, experimenteer bijvoorbeeld met de balpositie, afstand tot de bal, verschillende wedges, etc. en observeer het effect hiervan op de balvlucht en rol.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_04','Trail arm','golfskills','["hogeappr"]'::jsonb,'In deze oefening gaan we trainen op radiuscontrole. De radius van de beweging kan uitgelegd worden als de afstand van het clubhoofd tot aan het borstbeen. De mate waarin een speler controle heeft over de radius zal samen met andere factoren invloed hebben op de diepte (vertical lowpoint) van de zwaai en zodoende veel invloed hebben op de grondinteractie en uiteindelijk op de kwaliteit van het contact met de bal.','Gebruik voor deze oefening een wedge. Neem je normale set up in en pak vervolgens de club halverwege de grip vast met je trail hand (rechts voor rechtshandige spelers). Je legt je lead hand (links voor rechtshandige spelers) op je trail bovenarm en drukt deze zachtjes tegen je torso. Vanuit hier speel je de bal waarbij het contact tussen je torso en arm behouden blijft. Start met deze oefening eerst vanuit een semi rough ligging of vanaf een korte tee en werk vanuit naar een fairway ligging toe.','Experimenteer met verschillende grashoogtes.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_05','T-rex','golfskills','["hogeappr"]'::jsonb,'Je gaat leren om je lichaam en armen goed te laten samenwerken in de beweging en een constante radius te houden.','Kies een hoge approach situatie waarbij de speelplek op de fairway is op net iets minder dan de helft van de totale afstand van de rand van de green en ±15 meter van de hole. Ga rechtop staan met een smalle stand en de bal midden tussen je voeten gepositioneerd. Strek je armen en de club voor je uit dat club en armen een rechte lijn vormen door je polsen zijn nu vrijwel maximaal ontknikt. Trek je elle bogen vervolgens in zodat je bovenarmen contact maken met je bovenlichaam, buig nu voorover en adresseer de club achter de bal. Maak vanuit deze positie een symmetrische beweging met je lichaam als motor van de zwaai en waarbij het contact tussen bovenlichaam en bovenarmen gedurende de gehele zwaai behouden blijft.','Een andere manier om de connectie van armen en lichaam te trainen is door een handdoek of 2 headcovers onder je oksels en speel verschillende hoge approaches waarbij de handdoek onder je oksels blijft zitten.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_06','Ladder','golfskills','["lageappr"]'::jsonb,'In deze oefening gaan we trainen op het doseren van de afstand. Om de bal bij zo dicht mogelijk bij de hole te krijgen met een lage approach is het onder andere cruciaal om de afstand goed te doseren.','Maak op een redelijk vlak stuk green een rij met tees waarbij de verste tee op 20 meter van de speelplek en de dichtstbijzijnde op 8 meter van de speelplek staat en er telkens 2 meter afstand tussen de tees zit. Speel vanaf een fairway ligging de bal met als doel om de bal binnen een stoklengte te stoppen bij een vooraf bepaalde tee. Werk in eerste instantie in serie door bijvoorbeeld te starten bij de voorste tee en daarna eentje verder, etc. totdat je elke tee hebt gehaald. Wanneer je beter wordt kan je overgaan naar meer random training door lang, kort en middenafstanden met elkaar af te wisselen.','Je kunt deze oefening eenvoudig makkelijker of moeilijker maken door het einddoel (binnen 1 stoklengte) te verkleinen of vergroten, meer of minder afstanden uit te zetten, de afstanden tussen de tees te verkleinen, de speelafstand te verkleinen of vergroten of de speelsituatie te veranderen door bijvoorbeeld fairway en semi-rough af te wisselen of de tees in een uphill/downhill situatie uit te zetten, of de opdracht moeilijker te maken door bijvoorbeeld 2 ballen achter elkaar binnen een stoklengte te laten eindigen. Maak er een completion drill van door alle tees gehaald te hebben of 3 kansen per tee waarvan er 1 of meerdere in binnen 1 clublengte van de tee moeten eindigen. Of juist een scorekaart opdracht waarbij je random alle tees probeert de halen met 1 bal, waarbij gehaald doel 1 punt is.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_07','Low point control','golfskills','["hogeappr"]'::jsonb,'In deze oefening ga je trainen om het laagste punt van de zwaai, ook wel low point genoemd, zowel horizontaal als verticaal (zwaaidiepte) op een functionele plek ten opzichte van de bal te hebben. Met name de verticale component heeft enorm veel invloed op het grondcontact van de club en zodoende veel invloed op de kwaliteit van het contact met de bal. Het is dus van groot belang om hier controle over te hebben.','Kies een hoge approach situatie waarbij de speelplek op de fairway is op net iets minder dan de helft van de totale afstand van de rand van de green en ±15-30 meter van de hole. Gebruik een korte tee ±3 cm en tee de bal ±1cm boven grond op. Speel de bal waarbij je wel de tee raakt maar niet de grond. Wanneer dit regelmatig lukt (bijvoorbeeld 4 uit 5 keer) dan is het tijd om te gaan variëren door bijvoorbeeld afwisselend een bal vanaf de tee te spelen en daarna vanaf de grond. Of tee 5 ballen op met allemaal verschillende hoogtes en probeer de bal in alle situaties zuiver te raken.','Een variatie op dit thema is om een zuiver geraakte hoge approach uit de bunker te slaan, hier krijg je meteen feedback over de diepte van de zwaai en waar de club het zand raakt ten opzichte van de bal (zie low point control distance wedges).','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_08','Flight control','golfskills','["hogeappr"]'::jsonb,'De hoogte waarmee een schot gespeeld wordt zal onder andere veel invloed hebben op de hoeveelheid rol die de bal zal krijgen en zodoende uiteindelijk ook op de totale afstand. In deze oefening gaan we trainen om de vertrekhoek en daarmee de hoogte van de bal te beïnvloeden.','Kies een hoge approach situatie waarbij de speelplek op de fairway is op ongeveer een derde van de totale afstand van de rand van de green en ±15-30 meter van de hole. Het doel is om de bal binnen 2 meter van de hole te laten eindigen met achtereenvolgend een lagere, hogere en medium balvlucht. Het gaat hierbij om subtiele verschillen van bijvoorbeeld 1 meter hoog, 3 meter hoog en 2 meter hoog en niet de extremen aangezien dat meer speciale schoten zijn zoals het lobshot.

Er zijn verscheidene factoren die de uiteindelijke hoogte van de bal bepalen en zodoende ook verscheidene manieren om de hoogte van de bal te beïnvloeden. Een van die factoren waar we in deze oefening de nadruk leggen is de hoeveelheid loft op impact, oftewel de dynamische loft. De dynamische loft kunnen we onder andere beïnvloeden door:
Clubkeuze
Balpositie en shaftlean in set up (statisch)
Release (dynamisch)
Een combinatie van bovenstaande

Opdracht 1: speel achtereenvolgens de bal met je gap wedge (of pitching wedge), lob wedge en sand wedge om drie verschillende vluchthoogtes te krijgen en de bal binnen 2 meter van de hole te laten eindigen.

Opdracht 2: speel achtereenvolgens de bal met een balpositie achter het midden en veel shaftlean, een balpositie voorbij het midden en met een verticale shaft en uiteindelijk in het midden en een klein beetje shaftlean om drie verschillende vluchthoogtes te krijgen en de bal binnen 2 meter van de hole te laten eindigen.

Opdracht 3: speel vanuit een standaardbeginstand achtereenvolgens de bal met een eindstand waarbij de club nog naar beneden wijst waarbij er in het geval er water in de shaft zou zitten dit er niet uitloopt, naar boven wijst waarbij het water uit de grip zou lopen en uiteindelijk recht naar voren wijst om drie verschillende vluchthoogtes te krijgen en de bal binnen 2 meter van de hole te laten eindigen.','Experimenteer eens met combinaties van clubkeuze, statisch en dynamisch, of doe dezelfde opdrachten vanuit de rough.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_09','Hit the spot','golfskills','["hogeappr"]'::jsonb,'De afstand die de bal door de lucht vliegt, de carry, is een van de componenten die bijdraagt aan de totale afstand van de bal, het is dus van belang dat je hier controle over krijgt. In deze oefening ga je trainen om de carry naar wens te beïnvloeden.','Maak een landingsgebied op de green door 2 toursticks op 2 meter afstand van elkaar haaks op de speellijn te plaatsen. Leg 4x3 ballen op respectievelijk 6, 9, 12 en 15 meter van het landingsgebied, kan zowel op de fairway als rough. Begin bij de eerste afstand en speel respectievelijk 1 bal voorbij het landingsgebied, de volgende ervoor en de laatste in het landingsgebied. Is dit gelukt ga je door naar de volgende afstand. Start met de opdracht in serie te doen (van voor naar achter werken) en wanneer dit goed lukt dan ga je meer variabel te werk bijvoorbeeld 9, 15, 6, 12. Hoe beter je wordt hoe kleiner je de marges van voorbij, voor en de uiteindelijke landingszone kunt maken.

Om uiteindelijk nog beter te worden is het aan te raden om scherp te zijn op de variatie in hoogte waarmee je de bal speelt, hoe constanter deze is hoe constanter de landingshoek en hoe voorspelbaarder de hoeveelheid rol zal zijn en daarmee de totale afstand. Als je ziet dat er grote onbedoelde variatie in hoogte is dan is het wellicht verstandig om eerst meer tijd te spenderen aan het verbeteren van je vluchtcontrole.','Voeg afstanden toe, maak de marges kleiner of groter afhankelijk van je niveau, wissel fairway en rough situaties met elkaar af voor extra aanpassingsvermogen en doe deze oefening met vooraf bepaalde vluchthoogtes. Maak er een completion drill van door alle afstanden te voltooien of maak er een scorekaart opdracht van door vanaf elke plek 1 bal te slaan waarbij het raken van de landingszone 1 punt is en doe dat rondje 5 keer waardoor je in totaal 20 slagen hebt gedaan.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_10','Funny lies','golfskills','["hogeappr"]'::jsonb,'In deze oefening gaan we leren een ligging te lezen en wat deze ligging voor effect heeft op de vlucht en reactie van de bal op de green. Daarnaast ga je trainen hoe de uitvoering van de slag hierop aan te passen. Het lezen van een ligging, een goed voorspellend vermogen hebben en vervolgens de uitvoering kunnen aanpassen aan een bepaalde situatie zijn essentiële vaardigheden om zo veel mogelijk situaties succesvol op te kunnen lossen.','Zoek onderstaande liggingen op en speel meerdere hoge approaches naar eenzelfde doel. Probeer vooraf te beredeneren wat het gevolg van deze liggen zal zijn op de launch karakteristieken van de bal zoals: horizontal launch (vertrekrichting), launch vertical (vertrekhoek), spin, spinas, balsnelheid en probeer aan de hand van deze informatie eveneens de vlucht en de reactie van de bal op de green te voorspellen. 

We onderscheiden de volgende situaties:







Experimenteer met veel verschillende liggingen en wees niet bang om in dit proces vaak te ‘falen’, immers liever in training mee geëxperimenteerd en leren wat wel en niet kan dan dit in de wedstrijd uit te moeten vinden.','Experimenteer met veel verschillende liggingen','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_11','Pionnenjacht','golfskills','["lageappr"]'::jsonb,'Jezelf uitdagen in realistische spelsituaties en ontdekken in welke situaties jij jouw scherpe maar realistische doelen kunt halen en welke nog niet en dus eventueel extra aandacht behoeven.','Kies zelf een aantal veel voorkomende spelsituaties waarbij lage en hoge approaches door elkaar gespeeld worden en markeer de speelplekken met een pion (tee). Speel met 3 ballen per situatie per keer en stel jezelf een scherp maar realistisch doel wanneer jij tevreden bent met wat je wilt bereiken met deze 3 ballen. Een voorbeeld zou kunnen zijn: “ik wil 2 van de 3 ballen binnen 2 clublengten van de hole laten eindigen” of “alle drie binnen 3 clublengten”. Wanneer je het doel gehaald hebt mag je de pion weghalen en hoef je daar niet meer terug te komen, wanneer het doel niet gehaald is dan ga je door naar een andere situatie en dan kom je later weer terug voor een herkansing. Probeer alle situaties weg te spelen binnen een door jou gestelde tijd. Evalueer na de oefening welke situaties naar wens gingen en welke niet, kijk eveneens naar wat hier onderliggende redenen voor kunnen zijn en wat voor acties je naar aanleiding van deze oefening moet gaan doen om verder te verbeteren.','Varieer met aantal ballen per situatie, liggingen, afstanden en doelstellingen. Voeg andere spelsituaties zoals bunkerschoten, wedges en/of lobshots toe aan het parcours.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_12','Hole out','golfskills','["lageappr"]'::jsonb,'Door in je training te trainen op uitholen zal je dit ook steeds meer voor je zien tijdens het spelen en zodoende meer ballen daadwerkelijk uitholen dan wel dichter bij de hole laten eindigen.','Start bij deze oefening met wat voor jou eenvoudige chips zoals korte lage approaches van ±10 meter. Speel met 3 ballen en geef jezelf een bepaalde tijd, bijvoorbeeld 15 minuten, om in die tijd zoveel mogelijk van deze shots uit te holen. Of stel jezelf als doel om x ballen uit te holen en geef jezelf hier 30 minuten de tijd voor. Naar gelang je beter wordt kan je meer variatie en uitdaging in de situaties brengen.','Varieer met het aantal ballen die je per situatie mag spelen, varieer met afstanden en liggingen, voeg slagsoorten toe (laag, hoog, bunker) en hou bij hoeveel je van welke situatie hebt uitgeholed, speel tegen iemand anders en doe een wedstrijd wie als eerst (of in de minste slagen) op een parcours met x lage, x hoge en x bunkerschoten alle situaties heeft uitgeholed, etc.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_13','5 binnen 25','golfskills','["lageappr"]'::jsonb,'Inzicht krijgen of je vaardig genoeg bent om meerdere ballen achter elkaar dicht bij de hole te spelen.','Kies 5 verschillende lage of hoge approaches tussen de 10 en 30 meter. Het doel is om de totale restafstand van deze 5 schoten binnen 25ft te houden. Speel het schot en meet de restafstand tot aan de hole en trek deze van de oorspronkelijk 25 af, lukt het om na 5 schoten nog wat over te hebben? Niet gelukt? Start opnieuw, je krijgt 5 ‘starts’ om deze opdracht te voltooien.','Naast dat je dit met 5 lage of hoge approaches kunt doen kan je dit principe natuurlijk ook op andere slagsoorten toepassen of deze toevoegen aan de 5 te spelen situaties en verder kan je de totale restafstand en/of het aantal schoten aanpassen.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_14','Basistechniek bunkerslag','golfskills','["bunker"]'::jsonb,'Een belangrijk onderdeel van technisch goed onderlegd zijn en vooral ook blijven is met grote regelmaat de ogenschijnlijk simpele dingen heel goed doen. Basisvoorwaarden als een goed concept hebben over wat je wilt bereiken met de bal en zodoende impact, set up, oplijnen, het vasthouden van de club en de uiteindelijke beweging passend bij het schot kunnen hierbij veelvuldig de revue passeren. Het aanleren en vervolgens goed onderhouden van jouw basistechniek van een standaard bunkerslag is zodoende dan ook van groot belang.','De intentie is om de bal met een medium hoogte bunkerslag uit de bunker te spelen, kies zodoende ook een situatie die daadwerkelijk uitnodigt om dit schot te spelen. Een vlakke ligging op minimaal 2m afstand van de rand van de bunker en 10-25 meter van de hole is een prima uitgangspositie. Voor deze slag gebruiken we een sand- of lobwedge afhankelijk van jouw wedge set up. Speel de bal naar de hole waarbij je aandacht besteed aan het hele plaatje zoals je dat met jouw coach geschetst hebt te denken aan: de intentie wat je wilt met de bal, beginstand, beweging en eindstand. Hierbij kan gedacht worden aan:

Clubblad open
Brede stand breedte
Voorste voet een ±45 graden naar het doel gedraaid (geflared)
Neus op de plek waar je het zand wilt raken
Afhankelijk van de zandcondities meer of minder gewicht op links maar over het algemeen 60-40
Balpositie aan doelzijde van borstbeen
Shaft verticaal
‘Polsset’ combinatie van polsknik en onderarm rotatie vroeg in de achterzwaai
‘U shape’ swing
Bovenlichaam mee laten draaien op een stabiele basis
Release waarbij je de loft op de club houdt
Gelijkmatig tempo
Zwaailengte symmetrisch houden','Vanuit deze standaarduitvoering zijn er vele variaties mogelijk, experimenteer bijvoorbeeld met de balpositie, afstand tot de bal, bladstand, verschillende wedges, etc. en observeer het effect hiervan op de balvlucht en rol. Experimenteer ook eens met een radicaal andere club zoals een ijzer 9, 7 of 5, welke parameters moet je dan aanpassen om een functionele bunkerslag uit te voeren?','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_15','Smile to the clubface','golfskills','["bunker"]'::jsonb,'Leren met een open blad te spelen en zodoende de loft en bounce op de club te houden.','Teken met een marker een smiley op je clubface. Adresseer voor een standaard bunkerschot. Maak een paar slow motion oefenswings waarbij je kan controleren of je in de beginstand, top achterzwaai, impact en in de eindstand de smiley recht aan kunt kijken. Op deze manier hou je het blad gedurende de gehele beweging open. Wanneer je het gevoel voor de beweging hebt speel je een bal met hetzelfde gevoel, controleer in de eindstand of je de smiley wederom recht kunt aankijken.','Doe deze oefening ook eens met alleen lead en trail hand','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_16','Trail arm','golfskills','["bunker"]'::jsonb,'In deze oefening ga je trainen op een functionele trail arm (rechts voor een rechtshandige speler) en handactie, alsmede de samenwerking met de lichaamsactie en tempo van de beweging.','Kies een bunkersituatie van ±10-15m met een vlakke ligging op minimaal 2m afstand van de rand van de bunker. Voor deze oefening gebruiken we een sand- of lobwedge afhankelijk van jouw wedge set up. Adresseer voor een standaard bunkerschot (zie baseline bunkerslag). Haal vervolgens je lead hand (links voor rechtshandige spelers) van de club en plaats deze op de trail bovenarm (rechts voor rechtshandige spelers). Speel vanuit deze beginstand de bal met een vloeiende beweging van 9 tot 3 uit de bunker waarbij je zorgt dat je trail arm contact houdt met je bovenlichaam.','Als dit nog te uitdagend is vanuit een normale ligging dan kan je de bal op een klein hoopje zand leggen.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_17','Axis','golfskills','["bunker"]'::jsonb,'Teveel en/of inconsistente laterale beweging kan leiden tot inconsistent zandcontact en zodoende bemoeilijken om uit de bunker te komen dan wel enige controle te hebben over afstand, hoogte en spin. In deze oefening ga je trainen om rond 1-as te bewegen met als doel om de kans op consistent zandcontact te vergroten.','Kies een bunkersituatie van ±10-20m met een vlakke ligging op minimaal 2m afstand van de rand van de bunker. Voor deze oefening gebruiken we een sand- of lobwedge afhankelijk van jouw wedge set up. Adresseer voor een standaard bunkerschot (zie baseline bunkerslag) met de bal tegenover je voorste voet (links voor rechtshandige spelers) en zet vervolgens je achterste voet (rechts voor rechtshandige spelers) op de punt achter je. Speel vanuit deze beginstand de bal uit de bunker waarbij je je balans kunt houden tot en met de eindstand.','Als je het moeilijk vindt om op 1 been te balanceren dan kan je ook een stok in de grond naast je hoofd plaatsen waardoor je deze zal raken als je teveel van het doel weg beweegt.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_18','Lowpoint conrol','golfskills','["bunker"]'::jsonb,'In deze oefening ga je trainen om het laagste punt van de zwaai, ook wel low point genoemd, zowel horizontaal als verticaal (zwaaidiepte) op een functionele plek ten opzichte van de bal te hebben. Ook in de bunker is het belangrijk om controle te hebben over het laagste punt van de zwaai. Dit heeft namelijk veel invloed op de plek waar de club het zand in gaat (entry point) alsmede hoe diep de club het zand in zal gaan en zodoende dus veel invloed op hoeveel energie over gebracht kan worden op de bal. Deze oefening is gericht hoe deze te beïnvloeden.','Kies een bunkersituatie van ±20 meter met een vlakke ligging en wat afstand tot de rand van de bunker.

Opdracht 1: sla de bal vanuit een baseline set up clean uit de bunker waarbij er nagenoeg geen zandcontact is
Opdracht 2: sla de bal vanuit een baseline set up ‘zwaar’ uit de bunker waarbij er vrij diep zandcontact is
Opdracht 3: sla de bal vanuit een baseline set up ‘licht uit de bunker waarbij er vrij ondiep zandcontact is

Bij deze oefening heb je alle ruimte om voor elke opdracht oefenswings te maken om het voorgeschreven zandcontact op te zoeken. Maak bijvoorbeeld oefenswings totdat je 3x achter elkaar het gewenste zandcontact hebt en sla daarna je bal met dezelfde intentie. Is dit 2x achter elkaar gelukt met bal, ga dan door naar de volgende opdracht, lukt het niet dan kan je wat langer bij eenzelfde opdracht blijven. Lukt het helemaal niet, laat een professional je helpen.','Maak een tee van zand en speel de bal met je normale bunkertechniek. Maak 5 diepte categorieën waarbij 1 clean of the top is en 5 voor vrij diep in het zand staat, 3 zit hier tussenin, 2 is dan ondiep en 4 net wat zwaarder.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_19','Flight control','golfskills','["bunker"]'::jsonb,'De hoogte waarmee een schot gespeeld wordt zal onder andere veel invloed hebben op de hoeveelheid rol die de bal zal krijgen en zodoende uiteindelijk ook op de totale afstand. In deze oefening gaan we trainen om de vertrekhoek en daarmee de hoogte van de bal te beïnvloeden.','Kies een bunkersituatie van 10-20 meter met een vlakke ligging en wat afstand tot de rand van de bunker. Het doel is om de bal binnen 3 meter van de hole te laten eindigen met achtereenvolgend een lagere, hogere en medium balvlucht. Het gaat hierbij om subtiele verschillen van bijvoorbeeld 1 meter hoog, 3 meter hoog en 2 meter hoog maar schroom niet om ook eens de extremen op te zoeken om te kijken hoe hoog je de bal uit de bunker kunt krijgen over een bepaalde afstand.

Er zijn verscheidene factoren die de uiteindelijke hoogte van de bal bepalen en zodoende ook verscheidene manieren om de hoogte van de bal te beïnvloeden. Twee van die factoren waar we in deze oefening de nadruk leggen is de hoeveelheid loft op impact (dynamische loft) en de snelheid. De dynamische loft kunnen we onder andere beïnvloeden door:
Clubkeuze
Bladstand en shaftlean in set up (statisch)
Release (dynamisch)
Een combinatie van bovenstaande

Opdracht 1: speel achtereenvolgens de bal met je gap wedge (of pitching wedge), lob wedge en sand wedge om drie verschillende vluchthoogtes te krijgen en de bal binnen 2 meter van de hole te laten eindigen.

Opdracht 2: speel achtereenvolgens de bal met een recht blad en verticale shaft, flink open blad en weg van het doel leunende shaft, licht open blad en verticale shaft.

Opdracht 3: speel vanuit een standaardbeginstand achtereenvolgens de bal waarbij de grip voor het clubhoofd blijft door impact en een bal waarbij het clubhoofd de grip inhaalt door impact.','Experimenteer eens met combinaties van clubkeuze, statische en dynamische aanpassingen en observeer de verschillen in balvlucht. Een tourstick met een touwtje kan dienen als obstakel om de bal onder- of bovenlangs te spelen. Voeg de component snelheid toe, kijk wat er gebeurt met de hoogte wanneer je de bal met meer of minder snelheid speelt.','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_20','Funny lies','golfskills','["bunker"]'::jsonb,'In deze oefening gaan we leren een ligging te lezen en wat deze ligging voor effect heeft op de vlucht en reactie van de bal op de green. Daarnaast ga je trainen hoe de uitvoering van de slag hierop aan te passen. Het lezen van een ligging, een goed voorspellend vermogen hebben en vervolgens de uitvoering kunnen aanpassen aan een bepaalde situatie zijn essentiële vaardigheden om zo veel mogelijk situaties succesvol op te kunnen lossen.','Zoek onderstaande liggingen op en speel meerdere hoge approaches naar eenzelfde doel. Probeer vooraf te beredeneren wat het gevolg van deze liggen zal zijn op de launch karakteristieken van de bal zoals: horizontal launch (vertrekrichting), launch vertical (vertrekhoek), spin, spinas, balsnelheid en probeer aan de hand van deze informatie eveneens de vlucht en de reactie van de bal op de green te voorspellen. 

We onderscheiden de volgende situaties:







Experimenteer met veel verschillende liggingen en wees niet bang om in dit proces vaak te ‘falen’, immers liever in training mee geëxperimenteerd en leren wat wel en niet kan dan dit in de wedstrijd uit te moeten vinden.','Experimenteer met veel verschillende liggingen','ballen','','15','beide','["Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_21','Spot on','golfskills','["bunker"]'::jsonb,'De uiteindelijke afstand van de bal wordt door vele factoren bepaald, een aantal hiervan zijn de carry, hoogte en spin van de bal. In deze oefening ga je trainen om de carry, hoogte en spin te matchen om de bal bij de hole te laten eindigen.','Markeer 3 landing zones van elk 2 meter diep voor een vlag op ±20 meter afstand van de speelplek, Het doel is om achter elkaar de landingsgebieden te raken en de bal binnen 2 meter van de hole te laten eindigen. Hierbij zal de hoogte, carry en spin waarmee de bal gespeeld wordt dus goed op elkaar afgestemd moeten zijn. In deze ‘completion drill’ ben je klaar als dit achter elkaar gelukt is. Stel jezelf een doel binnen hoeveel tijd de opdracht voltooid moet zijn.','In deze oefening kan gevarieerd worden in de afstand van de speelplek t.o.v. de hole (of meerdere speelplekken achter elkaar), de diepte van de landingszones, hoe ver de bal van de hole mag eindigen, de tijd die je erover mag doen.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_22','Worst ball','golfskills','["bunker"]'::jsonb,'1 bal dicht bij de hole kan geluk zijn, meerdere achter elkaar is geen geluk meer. In deze oefening ga je testen of je vaardig genoeg bent om meerdere ballen achter elkaar dicht bij de hole te spelen.','Je speelt 3 ballen per spelsituatie, kies van deze 3 ballen de minst goede en probeer hier up & down mee te maken. Als je één van de drie uitholed telt deze als up & down ondanks dat dit dan de beste bal is. Speel 9 verschillende bunkerschoten tussen de 10 en 30m (bijvoorbeeld 3 vlak, 3 uphill, 3 downhill). Hoeveel up en downs kan je maken?','Bovenstaand is een scorekaart oefening gericht op up & downs je kunt ook de totale restafstand van je 9 minst goede ballen bijhouden en monitoren of dit over tijd steeds minder wordt. In plaats van een scorekaart opdracht kan je er ook een completion drill van maken door te proberen x up en downs gemaakt te hebben.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_23','Play as it lies','golfskills','["bunker"]'::jsonb,'Jezelf confronteren met de randomness van het spel en zodoende een veelvoud aan verschillende liggingen treffen waarbij je al je skills en aanpassingsvermogen nodig hebt om een resultaat te behalen.','Kies een willekeurige vlag op de bunkergreen. Pak 9 ballen in je handen en ga met je rug naar de bunker staan, gooi vervolgens in 1 worp alle 9 ballen blind in de bunker. Speel vervolgens alle 9 ballen zoals je ze aantreft naar dezelfde vlag op de green en blijf dit proces herhalen totdat je in totaal 6 ballen binnen 3 meter van de hole hebt geslagen. Geef jezelf hier een half uur de tijd voor om deze opdracht te voltooien. Pas de doelstelling aan op jouw niveau en hou deze scherp maar realistisch. Evalueer welke liggingen je goed afgaan en welke minder.','Pas de doelstelling aan: resultaat t.o.v. de hole groter of kleiner, x van de 9 binnen y. Kies een meer of minder uitdagende vlag en gooi de ballen vanuit een andere hoek in de bunker.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_24','Basistechniek distance wedge','golfskills','["distwedge"]'::jsonb,'Een belangrijk onderdeel van technisch goed onderlegd zijn en vooral ook blijven is met grote regelmaat de ogenschijnlijk simpele dingen heel goed doen. Basisvoorwaarden als een goed concept hebben over wat je wilt bereiken met de bal en zodoende impact, set up, oplijnen, het vasthouden van de club en de uiteindelijke beweging passend bij het schot kunnen hierbij veelvuldig de revue passeren. Het aanleren en vervolgens goed onderhouden van jouw basistechniek van een standaard distance wedge is zodoende dan ook van groot belang.','De intentie is om distance wedge schot te spelen (lange vluchtfase en weinig rol), kies zodoende ook een situatie die daadwerkelijk uitnodigt om dit schot te spelen. Een fairway ligging op ±30-90 meter van de hole. Voor deze slag gebruiken we afhankelijk van jouw afstanden en wedge set up een pitching-, gap-, sand- of lobwedge. Leg een tourstick op de grond tussen je voeten en de bal, parallel aan de bal-doellijn. Gebruik deze tourstick om de stand van het clubblad en je lichaamslijnen te controleren en zo nodig aan te passen. Vervolgens speel je de bal naar de hole waarbij je aandacht besteed aan het hele plaatje zoals je dat met jouw coach geschetst hebt te denken aan: de intentie wat je wilt met de bal, beginstand, beweging en eindstand. Hierbij kan gedacht worden aan:

Clubblad recht op doel
Standbreedte: buitenkant heupen buitenkant voeten
Gewicht met mate naar het voorste been door je borstbeen wat naar deze zijde te laten leunen
Voorste voet een ±30 graden naar het doel gedraaid (geflared)
Balpositie binnenkant linkerhiel
Grip voorkant bal
Samenwerking van handen, armen en lichaam
Club on plane
Beetje set
Extensie in de doorzwaai','Vanuit deze standaarduitvoering zijn er vele variaties mogelijk, experimenteer bijvoorbeeld met de balpositie, afstand tot de bal, bladstand, verschillende wedges, etc. en observeer het effect hiervan op de balvlucht en rol.','ballen','','15','beide','["Driving range","Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_25','Sleeppush','golfskills','["distwedge"]'::jsonb,'In deze oefening ga je trainen op een correcte lichaamsactie, samenwerking tussen lichaam en armen door de bal heen en het passeren van de gewenste impactpositie in de beweging.','Doe deze oefening met een wedge op de range of zoek een situatie met een vlakke fairway ligging op 40-60m tot de vlag. Maak een aantal oefenbewegingen waarbij je de club naast je (trail side) op de grond plaatst en vervolgens over de grond sleept naar een eindstand (zie video). Zorg dat lichaam, armen en handen de club gezamenlijk naar de eindstand brengen en voel dat de shaft lichtjes naar het doel leunt wanneer je impact passeert. Herhaal dit een paar keer en sla vervolgens je bal met hetzelfde gevoel.','Maak een video opname van de sleeppush en van de daadwerkelijke uitvoering om zelf te kunnen controleren of je de oefening goed uitvoert. Je kunt deze oefening ook doen door met een pw echt een bal te slepen, welke carry kan je halen?','ballen','','15','beide','["Driving range","Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_26','Lowpoint control','golfskills','["distwedge"]'::jsonb,'In deze oefening ga je trainen om het laagste punt van de zwaai, ook wel low point genoemd, zowel horizontaal als verticaal (zwaaidiepte) op een functionele plek ten opzichte van de bal te hebben. Met name de verticale component heeft enorm veel invloed op het grondcontact van de club en zodoende veel invloed op de kwaliteit van het contact met de bal. Het is dus van groot belang om hier controle over te hebben.','Kies een bunker op distance wedge afstand van de hole ±30m tot maximaal volle pitchingwedge afstand, voor deze oefening is een meter of 50 een prima startsituatie. Creëer een compact stukje zand in de bunker met behulp van de achterkant van de hark. Plaats de bal bovenop en speel de bal met een wedge slag (bij voorkeur met een halve of driekwart) naar het doel waarbij je de intentie hebt om de bal clean en zuiver te raken. Evalueer na elke slag het ‘entry point’ van de club in het zand alsmede de diepte van de slag en pas deze zo nodig dusdanig aan dat een zuiver contact met ondiepe ‘plag’ het gevolg is.','Door een bal vanaf een hoge tee te spelen train je ook je zwaaidiepte','ballen','','15','beide','["Driving range","Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_27','Flight control','golfskills','["distwedge"]'::jsonb,'De vertrekhoek (launch angle) waarmee een distance wedge gespeeld wordt zal onder andere veel invloed hebben op de hoogte en spin (en zodoende op de hoeveelheid rol) van de bal en zodoende uiteindelijk ook op de totale afstand. In deze oefening gaan we trainen op een launch angle van ±30 graden wat een goede richtlijn is voor standaard distance wedge schoten.','Voor deze oefening heb je 2 toursticks nodig, schone groeven, een fairway ligging waarbij er bij een goed contact geen vuil of gras tussen bal en club komt (een kunstgras afslagplek kan natuurlijk ook). Maak met de toursticks een ‘goal’ door deze op 1,5 meter afstand van de speelplek te plaatsen met het touwtje als ‘lat’ op 1 meter hoogte van de grond. 1 meter hoog op 1,5 meter afstand staat voor een vertrekhoek van ± 34 graden en het doel is om de bal onder de ‘lat’ door te laten vertrekken. 3 keer achter elkaar gelukt? Leg dan je de bal 25 centimeter naar achteren en speel de bal met dezelfde intentie.','Probeer de bal op verschillende hoogtes te lanceren','ballen','','15','beide','["Driving range","Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_28','Carry','golfskills','["distwedge"]'::jsonb,'De afstand die de bal door de lucht vliegt, de carry, is een belangrijke component die bijdraagt aan de totale afstand van de bal, het is dus van belang dat je hier controle over krijgt. In deze oefening ga je trainen om de carry naar wens te beïnvloeden.','Voor deze oefening maak je een landingsgebied op de green of op een stuk fairway van ±3m diep (voor betere feedback kan je hier ook een stuk afdekzeil voor gebruiken). Markeer verschillende afstanden t.o.v. het landingsgebied die je wilt gaan trainen, bijvoorbeeld 30, 40, 50 en 60 meter, dit kan zowel op de fairway als uit de rough zijn afhankelijk van welke ligging je wilt gaan trainen. Begin bij de eerste afstand en speel respectievelijk 1 bal voorbij het landingsgebied, de volgende ervoor en de laatste in het landingsgebied. Is dit gelukt ga je door naar de volgende afstand. Start met de opdracht in serie te doen (van voor naar achter werken) en wanneer dit goed lukt dan ga je meer variabel te werk bijvoorbeeld 40, 60, 30, 50. Hoe beter je wordt hoe kleiner je de marges van voorbij, voor en de uiteindelijke landingszone kunt maken.

Om uiteindelijk nog beter te worden is het aan te raden om scherp te zijn op de variatie in hoogte waarmee je de bal speelt, hoe constanter deze is hoe constanter de landingshoek en hoe voorspelbaarder de hoeveelheid rol zal zijn en daarmee de totale afstand. Als je ziet dat er grote onbedoelde variatie in hoogte is dan is het wellicht verstandig om eerst meer tijd te spenderen aan het verbeteren van je vluchtcontrole.','Voeg afstanden toe, maak de diepte van het landingsgebied groter of kleiner, maak de marges van voorbij en voor kleiner of groter afhankelijk van je niveau, wissel fairway en rough situaties met elkaar af voor extra aanpassingsvermogen en doe deze oefening met vooraf bepaalde vluchthoogtes. Maak er een completion drill van door alle afstanden te voltooien of maak er een scorekaart opdracht van door vanaf elke plek 1 bal te slaan waarbij het raken van de landingszone 1 punt is en doe dat rondje 5 keer waardoor je in totaal 20 slagen hebt gedaan.','ballen','','15','beide','["Driving range","Short game"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_29','Basecamp & set up check','golfskills','["fullswing"]'::jsonb,'Een belangrijk onderdeel van technisch goed onderlegd zijn en vooral ook blijven is met grote regelmaat de ogenschijnlijk simpele dingen heel goed doen. Basisvoorwaarden als een goed concept hebben over wat je wilt bereiken met de bal en zodoende impact, set up, oplijnen, het vasthouden van de club en de uiteindelijke beweging passend bij het schot dienen hierbij veelvuldig de revue te passeren. Hoewel een swing voor een groot deel een persoonlijke aangelegenheid is, is het onderhouden van een goede uitgangspositie voor iedereen een zinvolle tijdsbesteding, immers een goede uitgangspositie is een basisvoorwaarde voor goed bewegen. Dit is een van de redenen waarom je veel tourspelers veelvuldig zult zien trainen met toursticks en andere toevoegingen','Bepaal samen met jouw coach een goede uitgangspositie voor jou en creëer samen een ‘basisstation’ die jou helpt om deze beginstand zorgvuldig te kunnen trainen en onderhouden. 

Hierbij kan gedacht worden aan een ‘T’ opstelling met toursticks waarbij je de volgende zaken kunt controleren:

Clubbladstand in de richting waarin je wilt dat de bal vertrekt
Grip
Standbreedte en voetflare
Lichaamslijnen (voeten, knieën, heupen, torso, schouders, ogen)
Balpositie
Shaftlean
Balans: lead/trail en voor/achter
Houding','Maak een foto/video van jezelf om te kijken of je staat zoals jij dit met jouw coach hebt afgesproken.','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_30','Bends & tilts','golfskills','["fullswing"]'::jsonb,'Hoe de speler de club beweegt heeft invloed op de lichaamsactie en andersom, een effectieve lichaamsactie heeft zowel een positief invloed op de controle van de club als op de snelheid die gegenereerd kan worden. Deze oefening is erop gericht om een goed begrip en gevoel te krijgen hoe het lichaam in 3 dimensies beweegt in de golfswing.','Voor deze oefening heb je een hoepel nodig en 4 toursticks die je 2 aan 2 aan elkaar bevestigt met een elastiekje. Zoek een plek met een spiegel en positioneer jezelf zo dat je jezelf vanaf de zijkant (down the line) in de spiegel kunt zien. Pak de hoepel en plaats deze over je hoofd op schouderhoogte haaks op je wervelkolom en neem vervolgens je beginstand in. Vanuit deze positie ga je in slot motion een swing maken waarbij de hoepel in hetzelfde ‘vlak’ blijft. Om dit voor elkaar te krijgen zal het lichaam in de juiste verhoudingen 3 bewegingen naadloos moeten combineren te weten roteren (draaien om je lengteas), lateroflexie (zijwaarts buigen om je dwarse as) en flexie/extensie (voor- en achterwaarts buigen om je breedte as). Zodra je hier een goed gevoel voor hebt ga je door naar de oefening met club.

Zet twee lange stokken voor je neer in een hoek die haaks is op je wervelkolom in de set up en met wat ruimte ten opzichte van elkaar waar je hoofd royaal tussen past. Plak 2 stickers boven op elke schouder en maak nu oefenswings waarbij je voelt dat stickers in de vorm van de hoepel bewegen. Heb je hier een gevoel voor gekregen dan kan je een bal gaan slaan met dit gevoel. Begin met korte ijzers en kleinere swings.

Opmerking: pas op met de uiteindes van de stokken, vaak een goed idee om hier wat bescherming op te monteren. Kom je er niet uit raadpleeg dan je eigen coach om je hierbij te helpen.','Je kunt ook prima middels fysieke oefeningen aan dit principe werken door bijvoorbeeld 2 elastieken voor je op de grond te bevestigen en vervolgens de uiteinden vast te pakken en je beginstand in te nemen. Vanuit je beginstand trek je het elastiek naar achteren en omhoog, eerst je backswingkant en vervolgens je downswing kant.','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_31','Rocking','golfskills','["fullswing"]'::jsonb,'In elke golfswing vindt drukoverdracht plaats, in een effectieve golfswing gaat de druk onder de voeten in een vroeg stadium van de backswing naar rechts en vanaf gedurende de backswing alweer terug naar links. Deze oefening is erop gericht om deze effectieve ‘pressure’ shift te ontwikkelen en zodoende goed balcontact en snelheid te bevorderen.','Voor deze oefening heb je een rocking board nodig, dit is een plankje met een klein latje eronder waardoor dit een soort wipwap wordt. Ga op het plankje staan en neem je beginhouding in waarbij het voorste deel van het plankje op de grond rust. Vervolgens start je de backswing en beweegt de druk naar je trail side toe (rechts voor rechtshandige spelers) waardoor het plankje nu met de andere kant op de grond komt. Voordat de backswing geëindigd is beweeg je weer terug naar links waardoor de voorzijde van het plankje wederom op de grond komt waarna je de bal raakt.','Een variatie op deze oefening waarbij je geen bord nodig hebt is de dubbele stap. Maak een beginstand met je voeten tegen elkaar en bal tegenover je voorste voet. Neem vervolgens in een vloeiende beweging met je achterste voet (rechts voor rechtshandige spelers) eerst een stap opzij waarna je vervolgens de club in beweging brengt, halverwege de backswing zet je met je voorste voet een stap opzij en maak je de swing af naar de eindstand.','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_32','Sequence','golfskills','["fullswing"]'::jsonb,'We kunnen de golfer in een aantal verschillende grove segmenten opdelen te weten onderlichaam, torso, armen en club, deze segmenten kunnen in een bepaalde volgorde t.o.v. elkaar bewegen, dit wordt ook wel de kinematische volgorde genoemd. In een efficiënte golfswing gaat in de transitie (overgang van backswing naar downswing) eerst het onderlichaam roteren, gevolgd door de torso, daarna komen de armen en als laatste de club. Deze oefening is erop gericht om een efficiënte kinematische volgorde te ontwikkelen.','Start bij deze oefening met een mid ijzer. Neem je normale beginstand in, zet vervolgens je voorste voet (links voor een rechtshandige speler) naast je achterste voet en breng de club vervolgens in een positie voorbij de bal ±8 uur. Vanuit deze stand start je de backswing en ±halverwege de achterzwaai stap je uit met je voorste voet naar de originele positie van je normale beginstand en maak je de swing af naar een eindstand waarbij je de bal tegenkomt op de route.','Oefen deze beweging ook eens door met een (medicine) bal tegen de muur te gooien.','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U8","U10","U12","U14","Volwassenen"]'::jsonb,'["Kennismaking","Golfstart","Baanpermissie","hcp 54-36","hcp 36-18"]'::jsonb,'["F2","F3","A1"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_33','Lowpoint control','golfskills','["fullswing"]'::jsonb,'In deze oefening ga je trainen om het laagste punt van de zwaai, ook wel low point genoemd, zowel horizontaal als verticaal (zwaaidiepte) op een functionele plek ten opzichte van de bal te hebben.','Evalueer na elke slag het ‘entry point’ van de club in het zand alsmede de diepte van de slag en pas deze zo nodig dusdanig aan dat een zuiver contact met ondiepe ‘plag’ het gevolg is.','Door een bal vanaf een hoge tee te spelen train je ook je zwaaidiepte','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_34','9 ball','golfskills','["fullswing"]'::jsonb,'Trainen om de startrichting, curve en hoogte van de bal naar wens te beïnvloeden. Ondanks dat topspelers veelal een standaard balvlucht hebben in de vorm van een draw of fade met een bepaalde hoogte zijn zij over het algemeen in staat om desgevraagd een bepaalde vlucht te spelen waar het schot om vraagt. Denk hierbij bijvoorbeeld aan het spelen van een bepaalde hoogte en curve om obstakels te ontwijken of een bal onder of in de wind te houden. In deze oefening ga je 9 verschillende balvluchten trainen, enerzijds om je vaardigheidsniveau te vergroten, anderzijds om met deze kennis over je vaardigheid slimme keuzes te maken in de baan.','De opdracht is om met een mid ijzer negen balvluchten te spelen, te weten:
Draw: laag, hoog, midden
Fade: laag, hoog, midden
Recht: laag, hoog, midden

Kies een doel en plaats een tourstick op ±5 meter afstand op de bal doellijn. Speel achtereenvolgens alle balvluchten in bovenstaande (of zelf gekozen) volgorde, spreek met jezelf een aantal pogingen per vlucht af waarna je door mag naar de volgende ondanks dat het misschien niet gelukt is. Evalueer welke vluchten jou goed en welke vluchten jou minder goed afgaan.

Opmerking: mocht je niet goed weten hoe jij de balvlucht naar wens zou kunnen beïnvloeden neem dit dan eerst door met je eigen coach.','Doe deze oefeningen met andere clubs, of wissel van clubs tijdens een set balvluchten. Maak er een performance oefening van door op deze manier een balvlucht versie van boter kaas en eieren te spelen tegen een medespeler, of een scorekaart opdracht door te tellen hoeveel slagen je nodig hebt om alle vluchten af te kunnen vinken.','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_35','Funny lies','golfskills','["fullswing"]'::jsonb,'In deze oefening gaan we leren een ligging te lezen en wat deze ligging voor effect heeft op de vlucht en reactie van de bal op de green. Daarnaast ga je trainen hoe de uitvoering van de slag hierop aan te passen. Het lezen van een ligging, een goed voorspellend vermogen hebben en vervolgens de uitvoering kunnen aanpassen aan een bepaalde situatie zijn essentiële vaardigheden om zo veel mogelijk situaties succesvol op te kunnen lossen.','Zoek onderstaande liggingen op en speel meerdere hoge approaches naar eenzelfde doel. Probeer vooraf te beredeneren wat het gevolg van deze liggen zal zijn op de launch karakteristieken van de bal zoals: horizontal launch (vertrekrichting), launch vertical (vertrekhoek), spin, spinas, balsnelheid en probeer aan de hand van deze informatie eveneens de vlucht en de reactie van de bal op de green te voorspellen. 

We onderscheiden de volgende situaties:






Experimenteer met veel verschillende liggingen en wees niet bang om in dit proces vaak te ‘falen’, immers liever in training mee geëxperimenteerd en leren wat wel en niet kan dan dit in de wedstrijd uit te moeten vinden.','Experimenteer met veel verschillende liggingen','ballen','','15','beide','["Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'["U10","U12","U14","U16","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_36','Complete the bag','golfskills','["fullswing"]'::jsonb,'In deze oefening ga je testen hoeveel controle je hebt over de spreiding met al je clubs uit de tas.','Kies 2 punten op de range die samen een spreidingsgebied van ±5% van de afstand vormen (dus bijvoorbeeld 2 targets die ongeveer 10 meter uit elkaar staan op 200m). Haal alle clubs uit de tas. Start met je driver en speel 3 ballen, het doel is om 3 ballen achter elkaar binnen het spreidingsgebied te laten landen. Is dat gelukt dan mag de club in de tas, is het niet gelukt dan blijft deze buiten de tas en ga je door naar de volgende club. Je herhaalt deze opdracht met alle clubs (behalve de putter uiteraard) en daarna ga je de overgebleven clubs weg proberen te spelen.','Je kunt het spreidingsgebied breder of smaller maken, meer of minder ballen per club spelen, andere doelen stellen wat je met de ballen wilt bereiken (bijvoorbeeld 2 van de 4 binnen het gebied), de ballen spelen met een specifieke curve, etc.','ballen','','20','beide','["Driving range"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_37','Control your miss','golfskills','["fullswing"]'::jsonb,'In deze oefening gaan we trainen om de bal bewust aan een bepaalde kant van het doel te proberen houden. Een goede golfer slaat niet alleen goede ballen maar kan zich onderscheiden door ook enige controle te hebben over waar de bal gemist wordt in het geval dat de bal niet gaat volgens plan.','In dit voorbeeld gaan we linkerkant van het doel proberen te vermijden. Kies voor deze oefening een driver, lang ijzer, mid ijzer, kort ijzer en een wedge. Bepaal een spreidingsgebied van ±5% van de afstand. Speel achtereenvolgens een bal met elke club van driver naar wedge en herhaal dit totdat je met elke club 5 ballen hebt geslagen. De puntentelling is als volgt: rechts van het doel missen -1, in het spreidingsgebied +2 en links missen is -2. Hoeveel punten heb je gehaald?','Doe dezelfde oefening maar nu met het doel om de rechterkant van het doel uit het spel te halen, je kunt er ook een completion drill van maken door een doel te stellen dat je x punten moet halen voordat je mag stoppen.','ballen','','20','beide','["Driving range"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_38','Par-2 test','golfskills','["hogeappr"]'::jsonb,'Inzicht krijgen hoe jouw scorend vermogen is met betrekking tot je korte spel. In deze oefening ga je jezelf testen in verschillende short game situaties en proberen een zo laag mogelijke score te maken, door bepaalde gegevens bij te houden kan je later terugzien waar jou sterke en verbeterpunten liggen.','Doe deze oefening op rond de chippinggreen of in de (par-3) baan. Zet voor jezelf 3 lage approaches, 3 hoge approaches en 3 bunkerschoten uit kies hierbij 3 makkelijke, 3 moeilijke en 3 medium situaties qua moeilijkheidsgraad. Drop de bal op de speelplek, speel je bal en meet vervolgens de restafstand van je eerste slag tot aan de hole. Speel vervolgens door totdat de bal uitgeholed is en noteer de resultaten volgens onderstaande tabel. Wanneer je 9 holes gespeeld hebt kan je de totale score, aantal putts, totale & gemiddelde restafstand berekenen. Evalueer welke situaties goed en welke situaties minder gingen en waarom. Doe deze oefening regelmatig en hou je resultaten bij om je voortgang inzichtelijk te maken.


Opmerking: bij normale condities wordt er gedropt, wanneer de condities minder goed zijn zoals in een onderhoudsperiode kan je ervoor kiezen om representatief te plaatsen dan wel bijvoorbeeld 3 droppogingen te hebben.','Speel in plaats van 9 holes 18 holes en voeg indien mogelijk verschillende type schoten toe zoals distance wedges en/of lobshots, noteer liggingen om ook inzicht te krijgen in je prestaties uit verschillende liggingen.','ballen','','20','beide','["Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_39','Proximity','golfskills','["distwedge"]'::jsonb,'Inzicht krijgen hoe dicht je de bal bij de vlag slaat vanaf verschillende wedge afstanden.','Doe deze oefening in de (Par-3) baan. Speel op elke hole een distance wedge vanaf een fairway ligging, met een vrije zichtlijn over een afstand tussen de 30 meter en volle pitching wedge afstand. Noteer de startligging (voor nu dus even fairway) + startafstand, speel je bal en noteer vervolgens de restligging + afstand.


Hoeveel punten heb je na 9 holes en wat was de gemiddelde afstand? Of tel de restafstand op en deel deze door de totale beginafstand en vermenigvuldig deze met 100 dan heb je je proximity percentage (22,5/136*100 = 16,5%), een tourspeler zou hierbij uit willen komen op minder dan 5%.

Wanneer je deze oefening regelmatig doet dan kan je deze informatie ook gebruiken om bijvoorbeeld gemiddelde afstanden en/of punten te berekenen op bepaalde afstanden en analyseren hoe deze zich ten opzichte van elkaar verhouden. Zijn er wellicht afstanden waar je beter in bent dan andere en wellicht kan je deze informatie gebruiken om weer richting te geven aan je training alsmede gebruiken om keuzes te maken in de baan.','Varieer in met de ligging van de bal (fairway en rough door elkaar), bedenk een eigen puntensysteem bijvoorbeeld gebaseerd op % van de totale afstand (binnen 5% van de afstand = x punten).','ballen','','20','beide','["Driving range","Short game"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_40','Pressure putt','golfskills','["putten"]'::jsonb,'Op weg naar topgolf zal je als speler veelvuldig geconfronteerd worden met relatief korte putts die onder enige vorm van druk gespeeld moeten worden. Nu is het lastig om deze situatie exact na te bootsen maar enige vorm van druk in je training introduceren is altijd een betere voorbereiding dan niks. Deze oefening is erop gericht om veel variatie in je training te brengen en met regelmaat een putt onder druk te moeten spelen.','Kies een hole op een enigszins geonduleerd stukje green en plaats rond deze hole 5 tees op een afstand van 1.0-1.5 meter. Elke tee staat voor een opdracht, bijvoorbeeld:
3 10 meter putts naar eenzelfde doel, 2 ballen per situatie, doel: 4 ballen binnen 1 stoklengte
3 hoge approach afstanden (10, 15, 20m) naar eenzelfde vlag, 2 ballen per afstand, doel: 4 ballen binnen 2 stoklengten
3 hoge approach afstanden (15, 20, 25m) naar eenzelfde vlag, 2 ballen per afstand, doel: 4 ballen binnen 2 stoklengten
3 bunker afstanden (15, 20, 25m) naar eenzelfde vlag, 2 ballen per afstand, doel: 4 ballen binnen 3 stoklengten
3 lobshot afstanden (10, 20, 30m) naar eenzelfde vlag, 2 ballen per afstand, doel: 4 ballen binnen 3 stoklengten

Start bij een willekeurig onderdeel en probeer de opdracht te voltooien, is dat gelukt dan mag je door naar de corresponderende ‘pressure putt’, maak je die dan is deze situatie uitgespeeld. Zo niet dan moet je deze opdracht later nogmaals proberen te halen om nog een kans te hebben de pressure putt te maken. In het geval van het niet halen van de opdracht dan wel niet holen van de pressure putt ga je door naar een andere opdracht. Zo speel je door totdat er nog maar 1 opdracht over is en deze mag je dan achter elkaar blijven doen totdat ook deze ‘uitgespeeld’ is. Zorg in eerste instantie dat de doelstellingen realistisch en haalbaar zijn en maak je opdrachten steeds uitdagender.','In deze opdracht kan je eindeloos variëren en uitbreiden met slagsoorten, doelstellingen, liggingen, afstanden, etc. Als de oefenfaciliteiten redelijk bij elkaar in de buurt liggen dan kunnen er ook lange spel elementen toegevoegd worden aan het circuit zoals drives en ijzerslagen.','ballen','','20','beide','["Puttinggreen","Kunstgrasgreen"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_41','Par-18 wedgespel','spelen','[]'::jsonb,'Scoren met de scoring clubs onder telling.','Speel 9 wedge-holes (elk par 2) vanaf 40–100 m. Tel je totaalscore t.o.v. par 18 en probeer te verbeteren.','Varieer afstanden en liggingen; speel tegen een medespeler.','min','','30','beide','["Par-3 baan","Grote baan"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_42','Worst-ball 9 holes','spelen','[]'::jsonb,'Mentale weerbaarheid en consistentie onder druk.','Speel 9 holes met 2 ballen; je speelt telkens verder met de slechtste van de twee. Dwingt tot herhaalbaar spel.','Doe hetzelfde met alleen het korte spel of alleen approaches.','min','','30','beide','["Par-3 baan","Grote baan"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_43','Scenario-training druk','spelen','[]'::jsonb,'Omgaan met wedstrijdspanning en beslissingen.','Bedenk vooraf 3 wedstrijdscenario''s (bijv. laatste hole, 1 slag voorsprong). Speel ze met volledige routine en consequenties. Reflecteer na afloop.','Verhoog de inzet of speel de scenario''s tegen een tegenstander.','min','','30','beide','["Par-3 baan","Grote baan"]'::jsonb,'Individueel','','','[]'::jsonb,'["U12","U14","U16","U18","Volwassenen"]'::jsonb,'["Baanpermissie","hcp 54-36","hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief"]'::jsonb,'["F3","A1","A2","T1"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_44','Aandacht & focus','prestatiegedrag','[]'::jsonb,'Bewust sturen waar je aandacht naartoe gaat voor, tijdens en na de slag.','Oefen een vast aandachtsanker (bijv. de bal-doellijn of je ademhaling). Speel 10 slagen waarbij je telkens bewust je aandacht verlegt van breed (situatie inschatten) naar smal (uitvoering).','Voeg een afleider toe (geluid, tijdsdruk) en behoud je aandachtsanker.','min','','10','beide','[]'::jsonb,'Stations','','','[]'::jsonb,'["U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_45','Ademhaling & reset','prestatiegedrag','[]'::jsonb,'Spanning reguleren tussen slagen.','Oefen een reset: na een slechte slag 3 rustige buikademhalingen + een triggerwoord. Koppel dit aan 10 slagen zodat het automatisch wordt.','Pas de reset toe direct na een bewust geforceerde misser.','min','','10','beide','[]'::jsonb,'Stations','','','[]'::jsonb,'["U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_46','Visualisatie voor de ronde','prestatiegedrag','[]'::jsonb,'Mentaal de ronde en shots voorbereiden.','Ga 5–10 min voor de start rustig zitten en speel in gedachten de eerste holes: zie de shots, voel het ritme, bevestig je gameplan.','Visualiseer ook lastige holes en je reactie op een tegenslag.','min','','10','beide','[]'::jsonb,'Individueel','','','[]'::jsonb,'["U14","U16","U18","Volwassenen"]'::jsonb,'["hcp 36-18","hcp 18-9","Competitie recreatief","Competitie competitief","Selectie"]'::jsonb,'["A1","A2","T1","T2"]'::jsonb,'','performance','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_47','Rotatie-mobiliteit heup & thoracaal','fysiek','[]'::jsonb,'Bewegingsvrijheid voor de swing vergroten.','Doe 3 sets van heuprotaties, thoracale openers en swingsimulaties. Neem elke rotatie rustig tot eindstand. Ideaal als warming-up.','Bouw op naar dynamische versies vlak voor het slaan.','min','','10','beide','["Gym","Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_48','Rotatiekracht met medicine ball','fysiek','[]'::jsonb,'Explosieve rotatiekracht ontwikkelen.','Gooi een medicine ball zijwaarts tegen een muur, 3 sets van 8 per kant, met golf-achtige rotatie. Focus op snelheid vanuit de heupen.','Wissel af met lichte/zware bal om snelheid en kracht te trainen.','min','','10','beide','["Gym","Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'','skill','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08'),
('drill_seed_49','Balans single-leg','fysiek','[]'::jsonb,'Stabiliteit en balans in de swing verbeteren.','Sta 30 sec op één been (ogen dicht voor extra uitdaging), 3 sets per been. Voeg lichte swingbeweging toe voor sportspecifieke balans.','Sta op een instabiele ondergrond of maak halve swings op één been.','min','','10','beide','["Gym","Driving range"]'::jsonb,'Stations','','','[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'','techniek','[]'::jsonb,true,'goedgekeurd',null,'2026-10-08')
on conflict (id) do nothing;

